### ISSUE TITLE
Build with java 11 also

### ISSUE THREAD

**Issue by SemanticBeeng** [weso/shaclex#408]
`sbt test` fails partly because of 

```
java.lang.UnsupportedClassVersionError: es/weso/shex/parser/ShExDocLexer has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only re
cognizes class file versions up to 55.0hapeMapTest 4s                                                                                                                                                      
  | => eat es.weso.shex.compact.Parser$.parseSchemaReader(Parser.scala:130)                                                                                                                                
        at es.weso.shex.Schema$.fromInputStream(Schema.scala:224)                                                                                                                                          
        at es.weso.shex.Schema$.fromString(Schema.scala:302)                                                                                                                                               
        at es.weso.shacl.converter.shacl2ShExTest.$anonfun$shouldConvertSHACLShEx$6(shacl2ShExTest.scala:109)                                                                                              
        at cats.effect.IOFiber.next$2(IOFiber.scala:355)                                                                                                                                                   
        at cats.effect.IOFiber.runLoop(IOFiber.scala:363)                                                                                                                                                  
        at cats.effect.IOFiber.autoCedeR(IOFiber.scala:1174)                                                                                                                                               
        at cats.effect.IOFiber.run(IOFiber.scala:133)                                                                                                                                                      
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:383)       
```

According to https://stackoverflow.com/a/47457251/4032515 the published binaries were built with java 12.

Would it be possible to also publish binaries built with java 11?

**Comment by labra** [comment]
Thanks for your report, you are right that the published binaries were compiled with Java 12.

We have just published version `0.1.90` of shaclex compiled with Java 11. Can you try to see if it works now?

I will keep the issue open until we automate the publication of the binaries from github-workflows following issue #409
